name: Python application 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update zhihu
      run: |
        cd zhihu
        sh run.sh
    - name: Commit
      run: |
        git config --global user.email zhangli344236745@163.com
        git config --global user.name zhangli344236745
        git add .
        #git commit -m"action:`date +'%Y-%m-%d'`"
        git commit -m"action:`date`"
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
